### ISSUE TITLE
Strong mode support for polymorphic ?

### ISSUE THREAD

**Issue by dam0vm3nt** [gerald24/dynamo#4]
Hi, I'm very interested in using `dynamo` for a new project of mine.

I've tryied to use it in strong mode with a polymorphic model but it fails because the generated mixin for the subclass is invoking `super.` and this is forbidden.

Is there anyway to use polymorphic generation with dynamo that works with strong mode ?

**Comment by gerald24** [comment]
As written here https://www.dartlang.org/articles/language/mixins:
'Dart 1.13 and greater supports mixins that can extend from classes other than Object, and can call super.method(). This support is only available by default in the Dart VM and in Analyzer behind a flag. More specifically, it is behind the --supermixin flag in the command-line analyzer. ...'
Actually, tests are green with Dart 1.24.2, and I currently do not know how to activate the supermixin flag via analysis_options. `dartanalyzer --supermixin` will not complain about super calls.

**Comment by dam0vm3nt** [comment]
k! thanks. good to know.
